### ISSUE TITLE
Implement a robust live reload

### ISSUE THREAD

**Issue by roll** [okfn/opentrials-ebola-tracker#13]
For the upcoming development purpose (opentrials-prototype-app/tracker) we have to have more robust live reloading system using gulp and browsersync:

- [ ] application triggers reload on any code change
- [ ] static files trigger reload without page refreshing

**Comment by roll** [comment]
@pwalsh 

It's also not needed now. 

Than this issue and #16 I'll add somewhere (like wiki). It's things like good to have to start our future apps (ebola after prototyping etc).

**Comment by pwalsh** [comment]
@roll ok thanks. I'm going to get @kravets-levko to finish this UI in the coming days, FYI, as you are busy on Index right now.
