### ISSUE TITLE
Missin sorting on the leaderboard

### ISSUE THREAD

**Issue by pwalsh** [okfn/opentrials-ebola-tracker#25]
The leaderboard is sortable, and the default sort is "publication delay"

* [x] Add sorting
  * Option: publication delay
  * Option: participant count

@smth can you help please on the colour logic. the mock is a bit confusing for me.

* red: any "since completed"
* yellow: ?
* blue: ?

<img width="1280" alt="screenshot 2015-10-22 11 07 04" src="https://cloud.githubusercontent.com/assets/791678/10660076/0c94994a-78ad-11e5-8e01-37e83c43d90d.png">

**Comment by smth** [comment]
@pwalsh 
Red = Trial complete, no results published `.no-results`
Blue = Trial complete, results published
Yellow = Trial ongoing `.ongoing`

This is backed up by the text, but perhaps we need a key.

**Comment by pwalsh** [comment]
@kravets-levko as above for colouring on leaderboard.

**Comment by smth** [comment]
(There are corresponding classes in my markup)
